version: 2.1
commands:
  notify_job_status:
    description: Send webhook to trigger postman check
    steps:
      - run:
          name: On success
          when: on_success
          command: |
            curl https://slack-postman-test-ova72.transposit.io/api/v1/execute-http/webhook_circleci?api_key=pg7h7nsac7mpk0v8in7puce35f -d '{"payload":{"reponame":"'"$CIRCLE_PROJECT_REPONAME"'","branch":"'"$CIRCLE_BRANCH"'","build_parameters":{"CIRCLE_JOB":"'"$CIRCLE_JOB"'"},"outcome":"fixed","build_url":"'"$CIRCLE_BUILD_URL"'"}}' -H "Content-Type: application/json" -X POST --fail

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: exit 0
      - slack/notify:
          color: '#42e2f4'
          message: Your build has finished.
          webhook: https://hooks.slack.com/services/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
      - notify_job_status
orbs:
  slack: circleci/slack@3.3.0
workflows:
  your-workflow:
    jobs:
      - build
